name = "foam"
main = "src/index.ts"
compatibility_date = "2024-12-18"

[dev]
port = 8787

[durable_objects]
bindings = [
  { name = "PLAYER", class_name = "PlayerDO" },
  { name = "ROUTE", class_name = "RouteDO" },
  { name = "INTERSECTION", class_name = "IntersectionDO" },
  { name = "MARKET", class_name = "MarketDO" }
]

[[migrations]]
tag = "v1"
new_classes = ["PlayerDO", "RouteDO", "IntersectionDO", "MarketDO"]
